export type ToolCategory =
  | '電動ドライバー'
  | 'ドリルドライバー'
  | 'インパクトドライバー'
  | '丸ノコ'
  | 'ジグソー'
  | 'サンダー'
  | 'グラインダー'
  | 'マルチツール'

export type PowerSource = 'コード式' | 'バッテリー'
export type Level = 'beginner' | 'intermediate' | 'advanced'

export type Tool = {
  id: string
  name: string
  brand: string
  category: ToolCategory
  powerSource: PowerSource
  voltageOrWatt: string
  level: Level
  score: number
  price: string
  points: string[]
  verdict: string
  amazonQuery: string
  tags: string[]
}

export const toolCatalog: Tool[] = [
  {
    id: 'bdcdd12',
    name: 'Black+Decker BDCDD12',
    brand: 'Black+Decker',
    category: '電動ドライバー',
    powerSource: 'バッテリー',
    voltageOrWatt: '12V',
    level: 'beginner',
    score: 4.0,
    price: '約4,000〜5,000円',
    points: [
      '片手で持てるコンパクトサイズ。棚の組み立てや家具の取り付けに最適',
      '充電式で取り回しが良く、初めての電動工具に最適',
      'トルク調整機能付きで木材・金属どちらにも対応',
    ],
    verdict: '初めての電動工具として最もコスパが良い一台',
    amazonQuery: 'Black+Decker BDCDD12',
    tags: ['初心者', '入門', 'diy', '家具', '組み立て', '棚', 'コンパクト', '軽量', '安い'],
  },
  {
    id: 'bosch-easydrill-1200',
    name: 'Bosch EasyDrill 1200',
    brand: 'Bosch',
    category: 'ドリルドライバー',
    powerSource: 'バッテリー',
    voltageOrWatt: '12V',
    level: 'beginner',
    score: 4.2,
    price: '約6,000〜8,000円',
    points: [
      'Boschの入門モデル。品質の高さと使いやすさを両立',
      '2速切り替えでネジ締めと穴あけどちらもこなせる',
      '充電器・バッテリー2個付属でスターターセットとして完結',
    ],
    verdict: '信頼性の高いBosch入門機。長く使えるブランド品を選びたい初心者に',
    amazonQuery: 'Bosch EasyDrill 1200',
    tags: ['初心者', '入門', 'ドリル', '穴あけ', 'ネジ', 'ボッシュ', 'セット'],
  },
  {
    id: 'makita-df333d',
    name: 'Makita DF333DSHX',
    brand: 'Makita',
    category: 'ドリルドライバー',
    powerSource: 'バッテリー',
    voltageOrWatt: '10.8V',
    level: 'beginner',
    score: 4.4,
    price: '約10,000〜13,000円',
    points: [
      'マキタ入門機。コンパクト・軽量で女性や初心者にも扱いやすい',
      '21段トルク調整で様々な素材に対応',
      'バッテリーを他のマキタ10.8V製品と共用できる',
    ],
    verdict: 'マキタ品質を入門価格で。長くDIYをやるなら最初からこれを選ぶべき',
    amazonQuery: 'Makita DF333DSHX',
    tags: ['初心者', 'マキタ', '軽量', 'コンパクト', 'ドリル', '穴あけ', 'ネジ', 'diy'],
  },
  {
    id: 'ryobi-rse1250',
    name: 'RYOBI RSE-1250',
    brand: 'RYOBI',
    category: 'サンダー',
    powerSource: 'コード式',
    voltageOrWatt: '450W',
    level: 'beginner',
    score: 3.9,
    price: '約3,000〜4,000円',
    points: [
      '国産リョービの入門サンダー。価格の安さが魅力',
      'コード式で電池切れの心配なく広い面積を研磨できる',
      '集塵バッグ付きで作業後の掃除が楽',
    ],
    verdict: '木材の研磨・塗装前の下処理に。コスパ重視の入門機',
    amazonQuery: 'RYOBI RSE-1250 サンダー',
    tags: ['初心者', 'サンダー', '研磨', '塗装', 'リョービ', '安い', 'コード式', '木工'],
  },
  {
    id: 'makita-bo3710',
    name: 'Makita BO3710',
    brand: 'Makita',
    category: 'サンダー',
    powerSource: 'コード式',
    voltageOrWatt: '190W',
    level: 'beginner',
    score: 4.3,
    price: '約5,000〜7,000円',
    points: [
      'マキタのベストセラーサンダー。コンパクトで取り回しが良い',
      '集塵機能付きで粉塵を効率よく回収',
      '長時間使用でも疲れにくい設計',
    ],
    verdict: '木工DIYでサンダーを選ぶなら定番はこれ',
    amazonQuery: 'Makita BO3710',
    tags: ['サンダー', '研磨', 'マキタ', '木工', '集塵', 'コード式'],
  },
  {
    id: 'bosch-pst700e',
    name: 'Bosch PST 700 E',
    brand: 'Bosch',
    category: 'ジグソー',
    powerSource: 'コード式',
    voltageOrWatt: '500W',
    level: 'beginner',
    score: 4.1,
    price: '約8,000〜10,000円',
    points: [
      'Boschの入門ジグソー。曲線カットや自由な形に木材を切れる',
      'ブレード交換が工具不要で簡単',
      '速度調整ダイヤル付きで素材に合わせた切削が可能',
    ],
    verdict: '曲線や複雑な形のカットに入門するなら最初の一台',
    amazonQuery: 'Bosch PST 700 E ジグソー',
    tags: ['ジグソー', '曲線カット', '木工', 'ボッシュ', '初心者', 'コード式'],
  },
  {
    id: 'hikoki-ds10dbl2',
    name: 'HiKOKI DS10DBL2',
    brand: 'HiKOKI',
    category: 'ドリルドライバー',
    powerSource: 'バッテリー',
    voltageOrWatt: '10.8V',
    level: 'beginner',
    score: 4.2,
    price: '約8,000〜11,000円',
    points: [
      '工機ホールディングスの信頼性。プロ向けブランドの入門機',
      '小型・軽量でせまい場所での作業もしやすい',
      'バッテリーを他のHiKOKI 10.8V製品と共用可能',
    ],
    verdict: 'マキタと並ぶ信頼のHiKOKIブランドで入門したい人に',
    amazonQuery: 'HiKOKI DS10DBL2',
    tags: ['初心者', 'hikoki', '工機', 'ドリル', '小型', '軽量', 'バッテリー'],
  },
  {
    id: 'makita-td111d',
    name: 'Makita TD111DSHX',
    brand: 'Makita',
    category: 'インパクトドライバー',
    powerSource: 'バッテリー',
    voltageOrWatt: '10.8V',
    level: 'intermediate',
    score: 4.5,
    price: '約12,000〜16,000円',
    points: [
      '10.8Vクラス最強クラスのトルク。ウッドデッキや大型家具にも対応',
      'コンパクト&軽量で長時間作業でも疲れにくい',
      'マキタのバッテリー共用システムで拡張性が高い',
    ],
    verdict: 'DIYを本格的にやるなら絶対に持っておきたいインパクト入門機',
    amazonQuery: 'Makita TD111DSHX インパクトドライバー',
    tags: ['インパクトドライバー', 'マキタ', 'ウッドデッキ', '中級', 'diy', 'バッテリー', '10.8v'],
  },
  {
    id: 'makita-td171d',
    name: 'Makita TD171DRGX',
    brand: 'Makita',
    category: 'インパクトドライバー',
    powerSource: 'バッテリー',
    voltageOrWatt: '18V',
    level: 'intermediate',
    score: 4.7,
    price: '約30,000〜38,000円',
    points: [
      '18Vクラスのハイパワー。プロ仕様の作業量もこなせる',
      '防塵・防滴設計で屋外作業にも対応',
      '4段階の打撃モード切替で繊細な作業から大型ネジまで',
    ],
    verdict: '本格DIYからプロ作業まで対応するマキタの主力モデル',
    amazonQuery: 'Makita TD171DRGX インパクトドライバー',
    tags: ['インパクトドライバー', 'マキタ', '18v', 'プロ', '本格', 'ハイパワー', '屋外', '防塵'],
  },
  {
    id: 'makita-df484d',
    name: 'Makita DF484DRTX',
    brand: 'Makita',
    category: 'ドリルドライバー',
    powerSource: 'バッテリー',
    voltageOrWatt: '18V',
    level: 'intermediate',
    score: 4.6,
    price: '約25,000〜32,000円',
    points: [
      '18Vのパワーで金属・コンクリートにも対応',
      'ブラシレスモーターで長寿命かつ高効率',
      'マキタ18Vバッテリーシステムで他の工具と共用できる',
    ],
    verdict: '18Vシステムに移行するならまず買うべきドリルドライバー',
    amazonQuery: 'Makita DF484DRTX ドリルドライバー',
    tags: ['ドリル', 'マキタ', '18v', '中級', 'ブラシレス', '金属', 'コンクリート'],
  },
  {
    id: 'makita-hs301d',
    name: 'Makita HS301DSHE',
    brand: 'Makita',
    category: '丸ノコ',
    powerSource: 'バッテリー',
    voltageOrWatt: '10.8V',
    level: 'intermediate',
    score: 4.4,
    price: '約22,000〜28,000円',
    points: [
      '10.8Vのコンパクト丸ノコ。取り回しがよく室内DIYに最適',
      '刃径85mmで45mm以下の木材をスパッと切れる',
      'マキタ10.8Vバッテリー共用可能',
    ],
    verdict: '木材を直線カットしたい中級DIYerの最初の丸ノコ',
    amazonQuery: 'Makita HS301DSHE 丸ノコ',
    tags: ['丸ノコ', 'マキタ', '10.8v', '木工', '直線カット', '中級', 'バッテリー'],
  },
  {
    id: 'makita-tm30d',
    name: 'Makita TM30DSHX',
    brand: 'Makita',
    category: 'マルチツール',
    powerSource: 'バッテリー',
    voltageOrWatt: '10.8V',
    level: 'intermediate',
    score: 4.3,
    price: '約18,000〜23,000円',
    points: [
      'アタッチメント交換で切断・研磨・はがしを一台でこなす',
      '狭い隙間や細かい場所の作業に強い',
      'マキタ10.8Vバッテリー共用可能',
    ],
    verdict: 'リフォーム・補修作業で一台あると確実に活躍する万能工具',
    amazonQuery: 'Makita TM30DSHX マルチツール',
    tags: ['マルチツール', 'マキタ', '10.8v', 'リフォーム', '補修', '万能', '中級'],
  },
  {
    id: 'makita-jv103d',
    name: 'Makita JV103DWE',
    brand: 'Makita',
    category: 'ジグソー',
    powerSource: 'バッテリー',
    voltageOrWatt: '10.8V',
    level: 'intermediate',
    score: 4.3,
    price: '約14,000〜18,000円',
    points: [
      'コードレスで取り回し抜群。屋外での木材カットに最適',
      '鉄板・アルミなど木材以外もブレード交換で対応',
      '軌道切り替えで荒削りから仕上げカットまで',
    ],
    verdict: '屋外や出張先でのカット作業にはコードレスジグソーが便利',
    amazonQuery: 'Makita JV103DWE ジグソー',
    tags: ['ジグソー', 'マキタ', '10.8v', 'コードレス', '木工', '曲線', '中級'],
  },
  {
    id: 'hikoki-g10by',
    name: 'HiKOKI G10BY',
    brand: 'HiKOKI',
    category: 'グラインダー',
    powerSource: 'コード式',
    voltageOrWatt: '1,010W',
    level: 'intermediate',
    score: 4.4,
    price: '約8,000〜11,000円',
    points: [
      '1,010Wのパワーで金属の切断・研磨・バリ取りに対応',
      'ソフトスタート機能で起動時の跳ね返りを防止',
      '砥石・切断ディスクなど豊富なアクセサリーに対応',
    ],
    verdict: '金属加工・溶接後のバリ取りに必需品。中級以上の定番工具',
    amazonQuery: 'HiKOKI G10BY グラインダー',
    tags: ['グラインダー', 'hikoki', '金属', '切断', 'バリ取り', 'コード式', '中級'],
  },
  {
    id: 'makita-ga402',
    name: 'Makita GA402',
    brand: 'Makita',
    category: 'グラインダー',
    powerSource: 'コード式',
    voltageOrWatt: '720W',
    level: 'intermediate',
    score: 4.2,
    price: '約5,000〜8,000円',
    points: [
      'マキタの入門グラインダー。扱いやすい720Wで金属研磨に最適',
      '100mmディスクで細かい部分の研磨・切断が可能',
      '価格が安く工具セットとして揃えやすい',
    ],
    verdict: '金属を本格的に扱い始めるなら最初の一台',
    amazonQuery: 'Makita GA402 グラインダー',
    tags: ['グラインダー', 'マキタ', '金属', '研磨', 'コード式', '中級', '安い'],
  },
  {
    id: 'makita-td172d',
    name: 'Makita TD172DRGX',
    brand: 'Makita',
    category: 'インパクトドライバー',
    powerSource: 'バッテリー',
    voltageOrWatt: '18V',
    level: 'advanced',
    score: 4.8,
    price: '約42,000〜50,000円',
    points: [
      '18Vフラッグシップモデル。最大トルク180N·mでプロ仕様',
      '振動・衝撃・防塵・防滴の4重保護でどんな環境でも使える',
      'LED照明3灯搭載で暗所作業も問題なし',
    ],
    verdict: 'プロが現場で毎日使うレベルの信頼性と性能',
    amazonQuery: 'Makita TD172DRGX インパクトドライバー',
    tags: ['インパクトドライバー', 'マキタ', '18v', 'プロ', '業務用', '防塵', '防滴', '上級'],
  },
  {
    id: 'hikoki-c3606da',
    name: 'HiKOKI C3606DA',
    brand: 'HiKOKI',
    category: '丸ノコ',
    powerSource: 'バッテリー',
    voltageOrWatt: '36V',
    level: 'advanced',
    score: 4.7,
    price: '約50,000円〜',
    points: [
      '36Vマルチボルトで業務用コード式と同等のパワー',
      '刃径165mmで45mmの柱もワンカット',
      '防塵設計でホコリの多い現場でも安心',
    ],
    verdict: '現場でコード式と同性能を求めるプロ向けの最高峰',
    amazonQuery: 'HiKOKI C3606DA 丸ノコ',
    tags: ['丸ノコ', 'hikoki', '36v', 'プロ', '業務用', '現場', '上級', 'ハイパワー'],
  },
  {
    id: 'bosch-pmf190e',
    name: 'Bosch PMF 190 E',
    brand: 'Bosch',
    category: 'マルチツール',
    powerSource: 'コード式',
    voltageOrWatt: '190W',
    level: 'intermediate',
    score: 4.2,
    price: '約10,000〜14,000円',
    points: [
      'コード式190Wで電池切れを気にせず長時間作業できる',
      'StarLockシステムでアクセサリー交換が工具不要',
      '切断・研磨・はがしを一台でこなすオールラウンド性',
    ],
    verdict: 'リフォームDIYで幅広い作業をカバーしたい人向け',
    amazonQuery: 'Bosch PMF 190 E マルチツール',
    tags: ['マルチツール', 'ボッシュ', 'コード式', 'リフォーム', '中級', '長時間'],
  },
  {
    id: 'makita-hs631d',
    name: 'Makita HS631DPTJ',
    brand: 'Makita',
    category: '丸ノコ',
    powerSource: 'バッテリー',
    voltageOrWatt: '18V',
    level: 'advanced',
    score: 4.6,
    price: '約38,000〜45,000円',
    points: [
      '18V・刃径165mmでほとんどの木材をカット可能',
      'ブラシレスモーターで高効率・長寿命',
      'マキタ18Vバッテリーシステムと共用できる',
    ],
    verdict: '本格的な木工・大工仕事にはこの18V丸ノコが定番',
    amazonQuery: 'Makita HS631DPTJ 丸ノコ',
    tags: ['丸ノコ', 'マキタ', '18v', '木工', '大工', '上級', 'ブラシレス'],
  },
  {
    id: 'bosch-psm100a',
    name: 'Bosch PSM 100 A',
    brand: 'Bosch',
    category: 'サンダー',
    powerSource: 'コード式',
    voltageOrWatt: '100W',
    level: 'beginner',
    score: 4.0,
    price: '約5,000〜7,000円',
    points: [
      'デルタ形状で角や隅などの細かい部分を研磨できる',
      '100Wのコンパクトサイズで長時間作業もしやすい',
      '家具・工芸品の仕上げ研磨に最適',
    ],
    verdict: '家具の細かい部分や角の仕上げに特化したサンダー',
    amazonQuery: 'Bosch PSM 100 A サンダー',
    tags: ['サンダー', 'ボッシュ', '初心者', '細部', '仕上げ', 'コード式', '家具'],
  },
]
